### ISSUE TITLE
[NSDate today:@"device"]

### ISSUE THREAD

**Issue by kylefleming** [BadChoice/EasyDate#2]
Hey,

You mention using `NSDate *today   = [NSDate today:@"device"];` in the readme, but it doesn't seem to be implemented. Was it removed, or just not yet implemented?

**Comment by BadChoice** [comment]
What do you want to achieve exactly, get the start of day of the device?

**Comment by BadChoice** [comment]
I believe you can achieve it with this

`NSDate* today = [NSDate dateFor:@"today" timeZone:@"device" date:NSDate.date];`

But I think I can create a convenience method for it ;)

**Comment by kylefleming** [comment]
Yeah, that's what I ended up doing, I just noticed you have `[NSDate today:@"device"]` in the readme, but it doesn't actually work, so I thought I'd mention it.

**Comment by BadChoice** [comment]
I'll do a push now with those convenience methods ;)
